version: 2
updates:
  - package-ecosystem: "nuget"
    directory: "/UKHO.FmEssFssMock.API/UKHO.FmEssFssMock.API"
    schedule:
      interval: "weekly"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]
    groups:
      all-packages:
        patterns:
        - "*"
  - package-ecosystem: "nuget"
    directory: "/UKHO.PeriodicOutputService"
    schedule:
      interval: "weekly"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]
    groups:
      all-packages:
        patterns:
        - "*"
