parameters:
  - name: AzureSubscription
    type: string

steps:
  - task: PowerShell@2
    displayName: "terraform QCdeploy"
    inputs:
      targetType: filePath
      filePath: '$(Pipeline.Workspace)/mockapiterraformartifact/mock_api_terraform_run.ps1'
      arguments: '-deploymentResourceGroupName $(DeploymentResourceGroupName) -deploymentStorageAccountName $(DeploymentStorageAccountName) -workSpace $(Environment)'
    env:
      ARM_CLIENT_ID: $(TERRAFORM-CLIENT-ID)
      ARM_CLIENT_SECRET: $(TERRAFORM-CLIENT-SECRET)
      ARM_TENANT_ID: $(TERRAFORM-TENANT-ID)
      ARM_SUBSCRIPTION_ID: $(TERRAFORM-SUBSCRIPTION-ID)

  - task: FileTransform@1
    displayName: "File Transform: WebJob"
    inputs:
      folderPath: '$(Pipeline.Workspace)/PeriodicOutputService/*.zip'
      fileType: 'json'
      targetFiles: '**/appsettings.json'

  - task: AzureCLI@2
    displayName: "Mock API deployment"
    inputs:
      azureSubscription: "${{ parameters.AzureSubscription }}"
      scriptType: 'pscore'
      scriptLocation: 'scriptPath'
      scriptPath: '$(Pipeline.Workspace)/mockapiterraformartifact/mock_api_deployment.ps1'
      arguments: '-mockWebAppName $(mockWebAppName) -mockApipackagePath "$(Pipeline.Workspace)/MockWebAPI/UKHO.FleetManagerMock.API.zip" -webAppResourceGroup $(webAppResourceGroup)'
