name: $(BuildDefinitionName)_$(SourceBranchName)_$(Date:yy)$(DayOfYear).$(BuildCounter)

parameters:
  - name: ContinueEvenIfResourcesAreGettingDestroyed
    displayName: "Continue even if resources are getting destroyed"
    type: boolean
    default: false
  - name: disableStryker
    displayName: "Disable Stryker"
    type: boolean
    default: false

trigger:
  - main
  - release/*
  - develop

pool: 
    name: NautilusBuild
    demands: vs_16 -equals 1 #exclude agents 13 and 14 as code coverage report fails

variables:
  - name: BuildConfiguration
    value: "release"
  - name: BuildPlatform
    value: "any cpu"
  - name: BuildCounter
    value: $[counter(format('{0:yyyyMMdd}', pipeline.startTime), 1)]
  - name: UKHOAssemblyCompany
    value: "UK Hydrographic Office"
  - name: UKHOAssemblyVersionPrefix
    value: "1.0."
  - name: UKHOAssemblyProduct
    value: "Periodic Output Service"
  - name: UKHOAssemblyCopyright
    value: "Copyright © UK Hydrographic Office"
  - name: DeploymentPool
    value: "UKHO Ubuntu 1804"
  - name: Container
    value: "ukhydrographicoffice/terraform-azure-powershell-unzip:1.1.9"
  - name: WindowPool
    value: "NautilusBuild"

stages:
  
  - stage: PERFORM_DEPENDENCYCHECK_DOTNETBUILD_DOTNETTEST_AND_PUBLISH
    displayName: "Build (inc DependencyChecker, Dotnet Build , dotnet test and publish artifact )"
    dependsOn: []
    jobs:
      - job: DockerImagePull
        workspace:
          clean: all
        displayName: "DockerImagePullName"
        pool: $(DeploymentPool)
        steps:
          - task: PowerShell@2
            inputs:
              pwsh: true
              targetType: 'inline'
              script: |
                # Write your PowerShell commands here.
                docker pull wiremock/wiremock
                Write-Host "Hello World"
          